name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: |
          cd mon-app
          npm install

      - name: Build
        run: npm --prefix mon-app run build

      - name: Generate Version
        id: version
        run: echo "::set-output name=version::$(date +'%Y-%m-%d-%Hh-%M-%S')"

      - name: setup SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy
        run: |
          cd mon-app
          version=$(echo "${{ steps.version.outputs.version }}")
          scp -r -o StrictHostKeyChecking=no ./build ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_TARGET }}/build-$version
