name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: |
          cd mon-app
          npm install

      - name: Build
        run: npm --prefix mon-app run build

      - name: Add SSH key to agent
        run: |
          eval "$(ssh-agent -s)"
          ssh-add /home/runner/.ssh/deploy_key

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/runner/work/mon-app/mon-app
            git pull origin main
            git status
            npm install --only=prod
