name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        run: |
          scp -r mon-app maxime@51.178.30.100:/home/maxime/web
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
